const{chromium}=require('playwright'),{PNG}=require('pngjs'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.TEST_BASE,out=process.env.TEST_OUTPUT;if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(base))throw Error('只允许隔离测试');let browser;const count=Number(process.env.TEST_BATCH_COUNT||100);
async function login(p,password){await p.locator('#login-user').fill('admin');await p.locator('#login-pass').fill(password);await p.getByRole('button',{name:'登录',exact:true}).click()}
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.TEST_CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe'});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(base+'/sitelog/');await login(page,'Test-admin-initial-12345');await page.locator('#password-current').fill('Test-admin-initial-12345');await page.locator('#password-next').fill('Test-admin-ready-12345');await page.locator('#password-confirm').fill('Test-admin-ready-12345');await page.getByRole('button',{name:'保存新密码',exact:true}).click();await page.locator('#login-user').waitFor({state:'visible'});await login(page,'Test-admin-ready-12345');await page.waitForFunction(()=>Alpine.$data(document.body).draftOwner===1);
 const files=[];for(let n=0;n<count;n++){const png=new PNG({width:64,height:64});for(let i=0;i<png.data.length;i+=4){png.data[i]=n*2;png.data[i+1]=120;png.data[i+2]=210;png.data[i+3]=255;}files.push({name:'合成照片-'+n+'.png',mimeType:'image/png',buffer:PNG.sync.write(png)})}
 const started=Date.now();await page.locator('input[type=file][accept="image/*"]').first().setInputFiles(files);await page.waitForFunction(n=>Alpine.$data(document.body).images.length===n,count);await page.getByPlaceholder('项目名称',{exact:true}).fill('百张合成照片验收');
 const old=await page.evaluate(()=>Alpine.$data(document.body).accountJSON('',{html:'<p>批量识别期间分享可用性探针</p>',title:'隔离测试'}));let probing=true,probes=0,maxLatency=0;
 const probe=(async()=>{while(probing){const t=Date.now(),r=await context.request.get(base+'/s/'+old.id);assert.equal(r.status(),200);maxLatency=Math.max(maxLatency,Date.now()-t);probes++;await new Promise(r=>setTimeout(r,500));}})();
 await page.getByRole('button',{name:/AI 一键整理/}).click();await page.waitForFunction(n=>Alpine.$data(document.body).processedCount===n&&!Alpine.$data(document.body).processing,count,{timeout:240000});probing=false;await probe;const aiMs=Date.now()-started;assert.equal(await page.evaluate(()=>Alpine.$data(document.body).images.filter(x=>x._analyzed).length),count);
 await page.getByRole('button',{name:'保存云端工程',exact:true}).click();await page.waitForFunction(()=>Alpine.$data(document.body).cloudMessage.startsWith('云端已保存'),{},{timeout:120000});const syncMs=Date.now()-started-aiMs;await page.reload();await page.waitForFunction(n=>Alpine.$data(document.body).images.length===n,count);assert.equal(await page.locator('#images-container .node-block').count(),count);
 // 导出真实打印文档，保留中文文字层，并覆盖四种照片区域。
 await page.evaluate(()=>{const a=Alpine.$data(document.body),photos=a.images;a.images=photos.slice(0,2);a.arrivalImages=[{...photos[2],section:'arrival',title:'进场留底照片',desc:'进场照片中文验收标记'}];a.finishImages=[{...photos[3],section:'finish',title:'完工留底照片',desc:'完工照片中文验收标记'}];a.sopImages=[{...photos[4],title:'离场自检照片',itemKey:'water',desc:'水电门窗现场自检留底'}];a.projectName='中文分页与混合照片验收';a.fieldFacts.verification='人工补录：测试报告并非真实工程验收结论';a.syncToReport();a.syncFieldReport()});
 await page.getByRole('button',{name:'📥 导出 PDF',exact:true}).click();await page.getByRole('button',{name:'⬇️ 下载 PDF（文字可改）',exact:true}).click();const frame=await page.locator('iframe[aria-hidden=true]').elementHandle();assert.ok(frame);const printFrame=await frame.contentFrame();await printFrame.waitForLoadState();const printHTML=await printFrame.content();fs.writeFileSync(path.join(out,'实际打印文档.html'),printHTML);const pdfPage=await context.newPage();await pdfPage.setContent(printHTML);await pdfPage.evaluate(()=>document.fonts.ready);await pdfPage.pdf({path:path.join(out,'中文分页与照片验收.pdf'),preferCSSPageSize:true,printBackground:true});assert.equal(await pdfPage.locator('#report-content img').count(),5);await pdfPage.screenshot({path:path.join(out,'打印文档预览.png')});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'百张照片验收.json'),JSON.stringify({passed:true,photos:count,ai:'模拟上游，实际持久队列',ai_ms:aiMs,sync_ms:syncMs,share_probes:probes,max_share_latency_ms:maxLatency,pdf_photos:5,errors},null,2));console.log(JSON.stringify({passed:true,photos:count,ai_ms:aiMs,sync_ms:syncMs,share_probes:probes,max_share_latency_ms:maxLatency,pdf_photos:5}));
})().catch(async e=>{console.error(e);if(browser)for(const c of browser.contexts())for(const p of c.pages())try{await p.screenshot({path:path.join(out,'批量失败-'+Date.now()+'.png')})}catch{}process.exitCode=1}).finally(async()=>{if(browser)await browser.close()});
