"""Phase 3.8.30 企业智能体治理全链路追踪与统一审计智能层 —— 模型层。

定位（**复用而非重建**）：
- 3.8.21 ``agent_governance_workflow`` 回答「这条治理发现由谁负责、谁确认闭环」；
- 3.8.25 ``governance_workflow`` 回答「一条治理线索如何从发现走到归档」；
- 3.8.26 ``governance_dashboard`` 回答「人工在一个界面上能看到什么、确认什么」；
- **3.8.30 本层**回答「**这件事的全链路事实是什么、来自哪里、按什么顺序发生**」。

本层是**纯只读的事实串联层**：只把既有事实（事件 / 工作流 / 任务 / 审计 / 知识）
用 ``GovernanceTrace`` 串起来，并以时间线 / 重放 / 来源链三种只读视图呈现。它
**不产生任何新的治理判断**。

模型清单：
- 任务1：``GovernanceTraceSourceType`` / ``GovernanceTrace``（全链路唯一 trace）。
- 任务2：``GovernanceTraceLinkKind`` / ``GovernanceTraceLink``（**只建立关联**）。
- 任务3：``GovernanceAuditTimelineEntry`` / ``GovernanceAuditTimeline``（只读时间线）。
- 任务4：``GovernanceReplayStep`` / ``GovernanceReplayView``（**重建事实，禁止重新执行**）。
- 任务5：``SourceTrace`` / ``GovernanceTraceReport``（完整来源链）。

红线（fail-closed，三重拦截之「类型级 + 语义级」；结构级见 ``forbidden.py``）：
① 所有模型构造断言 ``safety_invariants_ok()``（engineering_enabled 必须 False）。
② 不承载 ``engineering_approved`` 语义；无任何 approve / sign 字段。
③ 禁 AI 自动修改治理记录：视图模型一律 ``frozen=True``（不可变），且经
   ``_AUDIT_MUTATION_MARKERS`` 语义扫描。
④ 禁 AI 自动生成治理结论：模型中**刻意不存在** ``conclusion`` / ``verdict`` /
   ``root_cause`` 字段；``GovernanceTraceReport.conclusion_included`` 恒为 False。
⑤ 禁 AI 自动关闭事件：模型中**刻意不存在** ``closed`` / ``resolved`` 字段；
   ``GovernanceReplayStep.re_executed`` 恒为 False（重放≠重新执行）。
⑥ 禁 AI 代替审计责任人：``requires_human_review`` 恒为 True，禁止置 False。
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Tuple

from agents.enterprise.agent_governance_workflow import _reject_markers
from agents.enterprise.audit import AuditActorKind
from agents.enterprise.governance_workflow.models import _reject_all_markers
from agents.enterprise.red_line import (
    EnterpriseRedLineViolationError,
    safety_invariants_ok,
)


# ---------------------------------------------------------------------------
# 追踪层专属语义标记（在 3.8.21 三组 + 3.8.25 三组之上增量补充第七/八/九组）
# ---------------------------------------------------------------------------

# 红线③：禁止出现「修改 / 删除 / 篡改治理记录」语义。
_AUDIT_MUTATION_MARKERS = (
    "auto_modify_audit",
    "auto modify audit",
    "modify_audit",
    "modify audit",
    "rewrite_audit",
    "rewrite audit",
    "auto_delete_record",
    "auto delete record",
    "delete_audit",
    "delete audit",
    "purge_audit",
    "tamper",
    "backdate",
    "篡改",
    "改写审计",
    "修改审计",
    "删除审计",
    "抹除记录",
    "销毁记录",
    "回填时间戳",
)

# 红线④：禁止出现「自动生成治理结论 / 自动定性定责」语义。
_CONCLUSION_MARKERS = (
    "auto_conclude",
    "auto conclude",
    "auto_generate_conclusion",
    "auto generate conclusion",
    "conclusion generated by ai",
    "concluded by ai",
    "ai_conclusion",
    "ai conclusion",
    "auto_verdict",
    "auto verdict",
    "auto_root_cause",
    "auto root cause",
    "root cause determined by ai",
    "自动结论",
    "自动生成结论",
    "自动得出结论",
    "ai结论",
    "ai 结论",
    "自动定性",
    "自动定责",
    "自动判定",
    "自动归因",
)

# 红线⑤：禁止出现「自动关闭 / 自动结案事件」语义。
_INCIDENT_CLOSURE_MARKERS = (
    "auto_close_incident",
    "auto close incident",
    "auto_resolve_incident",
    "auto resolve incident",
    "incident closed by ai",
    "auto_dismiss",
    "auto dismiss",
    "自动关闭事件",
    "自动结案",
    "自动销案",
    "自动消项",
    "自动解除告警",
)


def _reject_traceability_markers(text: str, *, ctx: str) -> None:
    """追踪层增量语义扫描（红线③/④/⑤），命中即抛红线违例。

    只读校验，**绝不改写文本**（改写等于 AI 悄悄美化事实）。
    """
    if not str(text).strip():
        return
    _reject_markers(
        text, _AUDIT_MUTATION_MARKERS,
        ctx=ctx, rule="治理记录不可变，禁止 AI 自动修改/删除/篡改审计（红线③）",
    )
    _reject_markers(
        text, _CONCLUSION_MARKERS,
        ctx=ctx, rule="治理结论只能由真实人工得出，禁止 AI 自动生成结论（红线④）",
    )
    _reject_markers(
        text, _INCIDENT_CLOSURE_MARKERS,
        ctx=ctx, rule="治理事件只能由真实人工关闭，禁止 AI 自动关闭/结案（红线⑤）",
    )


def _scan(text: str, *, ctx: str) -> None:
    """本层完整语义扫描 = 3.8.21 三组 + 3.8.25 三组 + 3.8.30 三组（共九组）。"""
    if not str(text).strip():
        return
    _reject_all_markers(text, ctx=ctx)
    _reject_traceability_markers(text, ctx=ctx)


def _clean_list(values, *, ctx: str) -> List[str]:
    out: List[str] = []
    for v in values or ():
        s = str(v).strip()
        if not s:
            continue
        _scan(s, ctx=ctx)
        out.append(s)
    return out


def _require_human_review_flag(flag: bool, *, ctx: str) -> None:
    if flag is not True:
        raise EnterpriseRedLineViolationError(
            f"{ctx} 禁止置 requires_human_review=False："
            f"治理事实的采信必须由真实审计责任人完成，AI 不得代替（红线⑥）"
        )


def _guard_activation(ctx: str) -> None:
    if not safety_invariants_ok():
        raise EnterpriseRedLineViolationError(
            f"safety_invariants_ok() 失败：禁止在启用态下构造 {ctx}（红线①）"
        )


# ---------------------------------------------------------------------------
# 任务7 载体：审计查看者（真实审计责任人）
# ---------------------------------------------------------------------------

@dataclass
class AuditViewer:
    """审计查看者载体（任务7：**同时承载「人工证明」与「角色权限」**）。

    追踪层的三道闸门需要两类信息，二者缺一不可：

    - ``actor_kind``：证明操作者是真实人工（交给 ``require_human_actor``，红线⑥）；
    - ``role``：交给 ``AgentPermissionPolicy`` 与 ``IdentityService`` 做审计数据
      隔离（红线⑥）。

    3.8.26 的 ``DashboardUser`` 只有前者，``identity.User`` 只有后者；本载体把两者
    组合起来，**不新增任何权限**，只是把既有身份事实原样转述。``has_permission``
    直接委派给 ``role``，因此 ``IdentityService.check(viewer, perm)`` 可直接使用。
    """

    actor_id: str = ""
    org_id: str = ""
    user: object = None          # identity.User（可选，用于自动填充）
    role: object = None          # identity.Role
    actor_kind: object = AuditActorKind.USER
    display_name: str = ""

    def __post_init__(self) -> None:
        src = self.user
        if src is not None:
            if not str(self.actor_id).strip():
                self.actor_id = str(getattr(src, "user_id", "") or "")
            if not str(self.org_id).strip():
                self.org_id = str(getattr(src, "org_id", "") or "")
            if self.role is None:
                self.role = getattr(src, "role", None)
            if not str(self.display_name).strip():
                self.display_name = str(getattr(src, "name", "") or "")
        self.actor_id = str(self.actor_id).strip()
        self.org_id = str(self.org_id).strip()

    @classmethod
    def from_user(cls, user: object, *, actor_kind: object = AuditActorKind.USER) -> "AuditViewer":
        """由 ``identity.User`` 构造查看者（**不改变任何权限事实**）。"""
        return cls(user=user, actor_kind=actor_kind)

    def has_permission(self, perm: object) -> bool:
        """委派给角色的权限判定（无角色 → 默认拒绝）。"""
        role = self.role
        if role is None:
            return False
        checker = getattr(role, "has", None)
        if checker is None:
            return False
        try:
            return bool(checker(perm))
        except Exception:
            return False

    def is_user(self) -> bool:
        return str(self.actor_kind).lower().endswith("user")


# ---------------------------------------------------------------------------
# 任务1-①：追踪来源类型
# ---------------------------------------------------------------------------

class GovernanceTraceSourceType(str, Enum):
    """治理链路来源类型（**只描述事实来自哪一层**，无任何处置态）。

    刻意**不提供** ``ai_conclusion`` / ``auto_determined`` 之类的来源：链路只能
    源自既有的**客观事实记录**，不能源自 AI 的判断（红线④）。
    """

    GOVERNANCE_EVENT = "governance_event"        # 治理事件（上游事实）
    GOVERNANCE_WORKFLOW = "governance_workflow"  # 3.8.25 编排工作流
    GOVERNANCE_TASK = "governance_task"          # 3.8.21 治理任务
    AUDIT_RECORD = "audit_record"                # 审计记录
    GOVERNANCE_KNOWLEDGE = "governance_knowledge"  # 3.8.22~3.8.24 治理知识
    SECURITY_RISK = "security_risk"              # 3.8.18 安全风险
    COMPLIANCE_RISK = "compliance_risk"          # 3.8.19 合规风险
    QUALITY_ISSUE = "quality_issue"              # 3.8.15 质量事实
    OBSERVABILITY_ANOMALY = "observability_anomaly"  # 3.8.14 运行事实
    HUMAN_REPORTED = "human_reported"            # 真实人工上报


# 禁止在类型层出现的字段名（结构级自检，供测试断言）。
_FORBIDDEN_TRACE_FIELDS = (
    "conclusion",
    "verdict",
    "root_cause",
    "judgement",
    "judgment",
    "closed",
    "resolved",
    "dismissed",
    "approved",
    "engineering_approved",
    "signed_by",
    "auto_conclusion",
)


# ---------------------------------------------------------------------------
# 任务1-②：治理链路追踪主体
# ---------------------------------------------------------------------------

@dataclass
class GovernanceTrace:
    """治理全链路追踪（任务1，**全链路唯一，只串事实，不下结论**）。

    ``trace_id`` 在同一组织内全链路唯一（唯一性由
    ``GovernanceTraceabilityService.register_trace`` 强制，重复即拒绝）。

    红线约束：
    - ``trace_id`` / ``source_id`` / ``created_at`` 任一为空即拒绝落库
      （无标识、无来源、无时序的「链路」不是事实，红线⑥：必须可溯源）；
    - 模型中**不存在** conclusion / verdict / root_cause / closed / resolved
      字段——「AI 给结论」「AI 关事件」在类型层面即不可表达（红线④/⑤）；
    - ``requires_human_review`` 恒为 True，禁止置 False（红线⑥）；
    - ``title`` / ``description`` / ``source_facts`` 经**九组语义扫描**，命中
      自动整改 / 自动分配 / 改权限 / 自动审批 / 自动执行 / 生成策略 / 改审计 /
      出结论 / 关事件 任一即拒绝；
    - 模型层**不提供**任何 conclude / close / modify / sign 方法。
    """

    trace_id: str
    source_type: GovernanceTraceSourceType = (
        GovernanceTraceSourceType.HUMAN_REPORTED
    )
    source_id: str = ""
    workflow_id: str = ""
    task_id: str = ""
    created_at: str = ""
    org_id: str = ""
    created_by: str = ""      # 创建者（AI 登记时如实记为 ai，不伪装为人工）
    title: str = ""
    description: str = ""
    source_facts: List[str] = field(default_factory=list)
    references: List[str] = field(default_factory=list)
    requires_human_review: bool = True

    def __post_init__(self) -> None:
        _guard_activation("GovernanceTrace")
        if not isinstance(self.source_type, GovernanceTraceSourceType):
            self.source_type = GovernanceTraceSourceType(self.source_type)

        self.trace_id = str(self.trace_id).strip()
        self.source_id = str(self.source_id).strip()
        self.workflow_id = str(self.workflow_id).strip()
        self.task_id = str(self.task_id).strip()
        self.created_at = str(self.created_at).strip()
        self.org_id = str(self.org_id).strip()
        self.created_by = str(self.created_by).strip()
        self.title = str(self.title).strip()
        self.description = str(self.description).strip()

        ctx = f"GovernanceTrace {self.trace_id!r}"
        if not self.trace_id:
            raise EnterpriseRedLineViolationError(
                "GovernanceTrace 缺少 trace_id：禁止落库无标识的治理链路（红线⑥）"
            )
        if not self.source_id:
            raise EnterpriseRedLineViolationError(
                f"{ctx} 缺少 source_id：禁止落库无来源的治理链路"
                f"（红线⑥：治理事实必须可溯源）"
            )
        if not self.created_at:
            raise EnterpriseRedLineViolationError(
                f"{ctx} 缺少 created_at：无时序的链路无法构成可审计事实（红线⑥）"
            )
        _require_human_review_flag(self.requires_human_review, ctx=ctx)

        _scan(self.title, ctx=f"{ctx}.title")
        _scan(self.description, ctx=f"{ctx}.description")
        self.source_facts = _clean_list(self.source_facts, ctx=f"{ctx}.source_facts")
        self.references = _clean_list(self.references, ctx=f"{ctx}.references")


# ---------------------------------------------------------------------------
# 任务2：链路关联（只建立关联）
# ---------------------------------------------------------------------------

class GovernanceTraceLinkKind(str, Enum):
    """链路关联目标类型（主理人明列五类）。

    ``event`` / ``workflow`` / ``task`` / ``audit`` / ``knowledge``。
    刻意**不提供** ``conclusion`` / ``decision`` 类目标：关联只能指向**既有事实
    对象**，不能指向 AI 产出的判断（红线④）。
    """

    EVENT = "event"
    WORKFLOW = "workflow"
    TASK = "task"
    AUDIT = "audit"
    KNOWLEDGE = "knowledge"


@dataclass
class GovernanceTraceLink:
    """治理链路关联（任务2，**只建立关联，不做任何处置**）。

    本模型是纯粹的「A 与 B 有关」这一事实声明：

    - 没有任何状态字段（无 ``closed`` / ``resolved`` / ``approved``）；
    - 没有任何结论字段（无 ``conclusion`` / ``verdict`` / ``root_cause``）；
    - ``note`` 仅允许承载**客观关联依据**，经九组语义扫描，命中即拒绝；
    - 模型层**不提供**任何 close / conclude / execute 方法。

    换言之：本层建立关联**不改变任何被关联对象的状态**（红线③/⑤）。
    """

    link_id: str
    trace_id: str
    link_kind: GovernanceTraceLinkKind = GovernanceTraceLinkKind.EVENT
    target_id: str = ""
    org_id: str = ""
    created_at: str = ""
    created_by: str = ""
    note: str = ""

    def __post_init__(self) -> None:
        _guard_activation("GovernanceTraceLink")
        if not isinstance(self.link_kind, GovernanceTraceLinkKind):
            self.link_kind = GovernanceTraceLinkKind(self.link_kind)

        self.link_id = str(self.link_id).strip()
        self.trace_id = str(self.trace_id).strip()
        self.target_id = str(self.target_id).strip()
        self.org_id = str(self.org_id).strip()
        self.created_at = str(self.created_at).strip()
        self.created_by = str(self.created_by).strip()
        self.note = str(self.note).strip()

        ctx = f"GovernanceTraceLink {self.link_id!r}"
        if not self.link_id:
            raise EnterpriseRedLineViolationError(
                "GovernanceTraceLink 缺少 link_id：禁止落库无标识的关联（红线⑥）"
            )
        if not self.trace_id:
            raise EnterpriseRedLineViolationError(
                f"{ctx} 缺少 trace_id：关联必须挂在具体链路上（红线⑥）"
            )
        if not self.target_id:
            raise EnterpriseRedLineViolationError(
                f"{ctx} 缺少 target_id：禁止建立指向空对象的关联"
                f"（红线⑥：关联必须可溯源）"
            )
        _scan(self.note, ctx=f"{ctx}.note")


# ---------------------------------------------------------------------------
# 任务3：统一审计时间线（只读）
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class GovernanceAuditTimelineEntry:
    """统一审计时间线条目（任务3，**不可变事实快照**）。

    主理人明列四要素：``ts`` / ``actor`` / ``action`` / ``source``。
    ``frozen=True`` 保证条目生成后**在类型层面不可修改**（红线③）。
    """

    entry_id: str
    ts: str
    actor_kind: AuditActorKind
    actor_id: str
    action: str
    source: str            # 事实来源标识（audit record_id / trace_id / …）
    source_kind: str       # 来源类别（audit / trace / link）
    target: str = ""
    detail: str = ""

    def __post_init__(self) -> None:
        _guard_activation("GovernanceAuditTimelineEntry")
        ctx = f"GovernanceAuditTimelineEntry {self.entry_id!r}"
        if not str(self.entry_id).strip():
            raise EnterpriseRedLineViolationError(
                "GovernanceAuditTimelineEntry 缺少 entry_id（红线⑥）"
            )
        if not str(self.source).strip():
            raise EnterpriseRedLineViolationError(
                f"{ctx} 缺少 source：时间线条目必须可溯源到既有事实（红线⑥）"
            )
        _scan(self.action, ctx=f"{ctx}.action")
        _scan(self.detail, ctx=f"{ctx}.detail")


@dataclass(frozen=True)
class GovernanceAuditTimeline:
    """统一审计时间线视图（任务3，**只读**）。

    - ``entries`` 为 ``tuple``（不可追加/删除），条目自身 ``frozen``（不可改写）；
    - ``read_only`` 恒为 True，禁止置 False；
    - ``requires_human_review`` 恒为 True：时间线只是**呈现**，采信与否由真实
      审计责任人决定（红线⑥）；
    - 视图中**不存在** conclusion / verdict 字段（红线④）。
    """

    trace_id: str
    org_id: str
    entries: Tuple[GovernanceAuditTimelineEntry, ...] = ()
    generated_at: str = ""
    generated_by: str = ""
    read_only: bool = True
    requires_human_review: bool = True

    def __post_init__(self) -> None:
        _guard_activation("GovernanceAuditTimeline")
        ctx = f"GovernanceAuditTimeline {self.trace_id!r}"
        if not isinstance(self.entries, tuple):
            raise EnterpriseRedLineViolationError(
                f"{ctx} entries 必须是不可变 tuple：时间线不得在生成后被追加或"
                f"删除（红线③）"
            )
        if self.read_only is not True:
            raise EnterpriseRedLineViolationError(
                f"{ctx} 禁止置 read_only=False：统一审计视图恒为只读（红线③）"
            )
        _require_human_review_flag(self.requires_human_review, ctx=ctx)


# ---------------------------------------------------------------------------
# 任务4：治理事实重放视图（重建事实，禁止重新执行）
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class GovernanceReplayStep:
    """重放步骤（任务4，**只重建事实，绝不重新执行动作**）。

    ``re_executed`` 恒为 False 且构造期强校验：一旦有人试图把重放标记成「已执行」，
    立即抛红线违例。这使「重放 → 重新执行」的退化在类型层面不可表达（红线④/⑤）。
    """

    seq: int
    ts: str
    actor_kind: AuditActorKind
    actor_id: str
    action: str
    source: str
    fact: str = ""            # 事实原文引用（不做任何改写与推断）
    re_executed: bool = False  # 恒 False

    def __post_init__(self) -> None:
        _guard_activation("GovernanceReplayStep")
        ctx = f"GovernanceReplayStep(seq={self.seq})"
        if self.re_executed is not False:
            raise EnterpriseRedLineViolationError(
                f"{ctx} 禁止置 re_executed=True：重放仅按时间序**重建既有事实**"
                f"供人工复核，绝不重新执行任何治理动作（红线④/⑤）"
            )
        if int(self.seq) < 0:
            raise EnterpriseRedLineViolationError(f"{ctx} seq 不得为负")
        if not str(self.source).strip():
            raise EnterpriseRedLineViolationError(
                f"{ctx} 缺少 source：重放步骤必须可溯源（红线⑥）"
            )
        _scan(self.action, ctx=f"{ctx}.action")
        _scan(self.fact, ctx=f"{ctx}.fact")


@dataclass(frozen=True)
class GovernanceReplayView:
    """治理事实重放视图（任务4，**只读重建**）。

    ``re_execution_performed`` 恒为 False —— 本视图的生成过程中没有、也不可能
    触发任何治理动作的重新执行。视图中**不存在** conclusion / closed 字段。
    """

    trace_id: str
    org_id: str
    steps: Tuple[GovernanceReplayStep, ...] = ()
    generated_at: str = ""
    generated_by: str = ""
    read_only: bool = True
    re_execution_performed: bool = False
    requires_human_review: bool = True

    def __post_init__(self) -> None:
        _guard_activation("GovernanceReplayView")
        ctx = f"GovernanceReplayView {self.trace_id!r}"
        if not isinstance(self.steps, tuple):
            raise EnterpriseRedLineViolationError(
                f"{ctx} steps 必须是不可变 tuple（红线③）"
            )
        if self.read_only is not True:
            raise EnterpriseRedLineViolationError(
                f"{ctx} 禁止置 read_only=False：重放视图恒为只读（红线③）"
            )
        if self.re_execution_performed is not False:
            raise EnterpriseRedLineViolationError(
                f"{ctx} 禁止置 re_execution_performed=True："
                f"重放绝不重新执行治理动作（红线④/⑤）"
            )
        _require_human_review_flag(self.requires_human_review, ctx=ctx)


# ---------------------------------------------------------------------------
# 任务5：来源链与追踪报告
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SourceTrace:
    """单条来源事实（任务5，**原样引用，不做推断**）。"""

    source_kind: GovernanceTraceLinkKind
    source_id: str
    ts: str = ""
    actor_id: str = ""
    summary: str = ""   # 事实摘要（原样引用；不得含结论语义）

    def __post_init__(self) -> None:
        _guard_activation("SourceTrace")
        if not isinstance(self.source_kind, GovernanceTraceLinkKind):
            object.__setattr__(
                self, "source_kind", GovernanceTraceLinkKind(self.source_kind)
            )
        ctx = f"SourceTrace {self.source_id!r}"
        if not str(self.source_id).strip():
            raise EnterpriseRedLineViolationError(
                "SourceTrace 缺少 source_id：来源链每一环都必须可溯源（红线⑥）"
            )
        _scan(self.summary, ctx=f"{ctx}.summary")


@dataclass(frozen=True)
class GovernanceTraceReport:
    """治理追踪报告（任务5，**完整来源链，不含任何结论**）。

    - ``source_chain`` 给出「这条链路的每一个事实分别来自哪里」；
    - ``timeline`` 复用任务3 的只读时间线；
    - ``conclusion_included`` 恒为 False：报告只汇总事实，**不生成治理结论**
      （红线④）；
    - ``requires_human_review`` 恒为 True：报告须由真实审计责任人研判（红线⑥）。
    """

    report_id: str
    trace_id: str
    org_id: str
    source_chain: Tuple[SourceTrace, ...] = ()
    timeline: "GovernanceAuditTimeline | None" = None
    generated_at: str = ""
    generated_by: str = ""
    read_only: bool = True
    conclusion_included: bool = False
    requires_human_review: bool = True

    def __post_init__(self) -> None:
        _guard_activation("GovernanceTraceReport")
        ctx = f"GovernanceTraceReport {self.report_id!r}"
        if not str(self.report_id).strip():
            raise EnterpriseRedLineViolationError(
                "GovernanceTraceReport 缺少 report_id（红线⑥）"
            )
        if not isinstance(self.source_chain, tuple):
            raise EnterpriseRedLineViolationError(
                f"{ctx} source_chain 必须是不可变 tuple（红线③）"
            )
        if self.read_only is not True:
            raise EnterpriseRedLineViolationError(
                f"{ctx} 禁止置 read_only=False：追踪报告恒为只读（红线③）"
            )
        if self.conclusion_included is not False:
            raise EnterpriseRedLineViolationError(
                f"{ctx} 禁止置 conclusion_included=True："
                f"追踪报告只汇总来源事实，治理结论只能由真实人工得出（红线④）"
            )
        _require_human_review_flag(self.requires_human_review, ctx=ctx)


__all__ = [
    "AuditViewer",
    "GovernanceTraceSourceType",
    "GovernanceTrace",
    "GovernanceTraceLinkKind",
    "GovernanceTraceLink",
    "GovernanceAuditTimelineEntry",
    "GovernanceAuditTimeline",
    "GovernanceReplayStep",
    "GovernanceReplayView",
    "SourceTrace",
    "GovernanceTraceReport",
    "_AUDIT_MUTATION_MARKERS",
    "_CONCLUSION_MARKERS",
    "_INCIDENT_CLOSURE_MARKERS",
    "_FORBIDDEN_TRACE_FIELDS",
    "_reject_traceability_markers",
]
