"""Phase 3.9.15 — Human Authorization Registry (T11).

Thin, fail-closed wrapper around the 3.9.14 DualKeyAuthorization base. The
Machine Safety Key can be generated by the system (it only proves the machine
side safety pre-conditions are met). The Human Authorization Key MUST be minted
by a real USER actor — the base dataclass enforces ``actor_kind == "USER"`` and
calls ``require_human_actor``; AI must never mint it.

This module does NOT re-implement the dual-key model; it reuses
``agents.external_staging_runtime.change_control`` and only adds a 3.9.15
terminal-state pin on the change-control verdict.
"""
from __future__ import annotations

import secrets
from typing import Optional

from agents.enterprise.red_line import EnterpriseRedLineViolationError
from agents.external_staging_runtime.change_control import (
    evaluate_change_control as _base_evaluate_change_control,
)

from .change_control import (
    ChangeControlVerdict,
    DualKeyAuthorization,
    HumanAuthorizationKey,
    MachineSafetyKey,
)
from .constants import LIVE_TERMINAL_STATE


def generate_machine_safety_key() -> MachineSafetyKey:
    """Machine Safety Key — system-generated; proves machine-side safety pre-conditions."""
    return MachineSafetyKey(
        token=secrets.token_hex(16),
        generated_by="machine",
        note="Machine Safety Key 仅证明系统侧安全前置；不构成人工授权。",
    )


def wrap_human_authorization_key(key: HumanAuthorizationKey) -> HumanAuthorizationKey:
    """Accept a Human Authorization Key already minted by a real USER.

    The base ``HumanAuthorizationKey`` already raises ``EnterpriseRedLineViolationError``
    if ``actor_kind != "USER"``, so simply returning it is a fail-closed validation:
    any attempt by AI to construct one with a non-USER actor will have already thrown
    before this function is ever reached.
    """
    if key.actor_kind != "USER":  # pragma: no cover - defensive; __post_init__ already guards
        raise EnterpriseRedLineViolationError(
            "Human Authorization Key 必须由真实 USER 持有；AI 不得 mint。"
        )
    return key


def make_dual_key(
    machine_key: MachineSafetyKey,
    human_key: Optional[HumanAuthorizationKey] = None,
) -> DualKeyAuthorization:
    """Assemble a dual-key authorization. ``human_key`` must come from a real USER."""
    return DualKeyAuthorization(machine_key=machine_key, human_key=human_key)


def evaluate_live_change_control(
    auth: Optional[DualKeyAuthorization] = None,
) -> ChangeControlVerdict:
    """3.9.15-pinned change-control verdict.

    Reuses the 3.9.14 evaluation logic (so all fail-closed invariants hold:
    ``real_apply_allowed=False``, ``is_go_or_approved=False``, ``is_production=False``)
    but pins the terminal state to Phase 3.9.15's BUILT_NO_GO terminal.
    """
    base = _base_evaluate_change_control(auth)
    return ChangeControlVerdict(
        apply_gate_state=base.apply_gate_state,
        four_role_signoff_required=base.four_role_signoff_required,
        human_actor_required=base.human_actor_required,
        dual_key_authorized=base.dual_key_authorized,
        is_production=base.is_production,
        real_apply_allowed=base.real_apply_allowed,
        terminal_state=LIVE_TERMINAL_STATE,
        detail=base.detail,
    )
