"""phase0_init_schema

Revision ID: d17f02429ce9
Revises: 
Create Date: 2026-07-23 22:07:41.683062

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from app.db.models.tenant import GUID


# revision identifiers, used by Alembic.
revision: str = 'd17f02429ce9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status in ('active', 'suspended', 'archived')", name=op.f('ck_tenants_tenant_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('agents',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status in ('active', 'disabled', 'experimental')", name=op.f('ck_agents_agent_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agents_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_agents_tenant_name')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('knowledge_cases',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scenario', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status in ('draft', 'verified', 'deprecated')", name=op.f('ck_knowledge_cases_knowledge_case_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_knowledge_cases_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_cases'))
    )
    with op.batch_alter_table('knowledge_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_cases_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('knowledge_rules',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status in ('draft', 'verified', 'deprecated')", name=op.f('ck_knowledge_rules_knowledge_rule_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_knowledge_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_rules')),
    sa.UniqueConstraint('tenant_id', 'category', 'key', 'version', name='uq_knowledge_rules_scope')
    )
    with op.batch_alter_table('knowledge_rules', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_rules_category', ['tenant_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('threshold_configs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status in ('draft', 'verified', 'deprecated')", name=op.f('ck_threshold_configs_threshold_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_threshold_configs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threshold_configs')),
    sa.UniqueConstraint('tenant_id', 'key', 'version', name='uq_threshold_configs_scope')
    )
    with op.batch_alter_table('threshold_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threshold_configs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role in ('admin', 'designer', 'sales', 'customer', 'worker')", name=op.f('ck_users_user_role_valid')),
    sa.CheckConstraint("status in ('active', 'suspended', 'invited')", name=op.f('ck_users_user_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_users_tenant_role', ['tenant_id', 'role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('actor_id', GUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action in ('create', 'update', 'delete', 'login', 'logout', 'export', 'import')", name=op.f('ck_audit_logs_audit_action_valid')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index('ix_audit_logs_target', ['tenant_id', 'target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('owner_id', GUID(), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=False),
    sa.Column('evidence_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state in ('Draft', 'Submitted', 'Analyzing', 'Designed', 'Quoted', 'Closed')", name=op.f('ck_projects_project_state_valid')),
    sa.CheckConstraint("status in ('pending', 'analysis', 'design', 'quotation', 'construction', 'completed')", name=op.f('ck_projects_project_status_valid')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_projects_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_projects_tenant_state', ['tenant_id', 'state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_tenant_state')
        batch_op.drop_index(batch_op.f('ix_projects_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index('ix_audit_logs_target')
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_tenant_role')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    with op.batch_alter_table('threshold_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threshold_configs_tenant_id'))

    op.drop_table('threshold_configs')
    with op.batch_alter_table('knowledge_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_rules_tenant_id'))
        batch_op.drop_index('ix_knowledge_rules_category')

    op.drop_table('knowledge_rules')
    with op.batch_alter_table('knowledge_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_cases_tenant_id'))

    op.drop_table('knowledge_cases')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_tenant_id'))

    op.drop_table('agents')
    op.drop_table('tenants')
    # ### end Alembic commands ###
